import { Product, User } from '@/types';

// ============================================
// Mock Users
// ============================================
export const mockUsers: User[] = [
    {
        id: 'user-1',
        name: 'Arjun Mehta',
        email: 'arjun.mehta@iitd.ac.in',
        avatar: '',
        role: 'seller',
        university: 'IIT Delhi',
        universityEmail: 'arjun.mehta@iitd.ac.in',
        isVerifiedStudent: true,
        phone: '+91 98765 43210',
        upiId: 'arjun@upi',
        rating: 4.8,
        totalRatings: 12,
        createdAt: '2025-08-15T10:00:00Z',
        updatedAt: '2026-01-20T14:30:00Z',
    },
    {
        id: 'user-2',
        name: 'Priya Sharma',
        email: 'priya.sharma@bits.ac.in',
        avatar: '',
        role: 'seller',
        university: 'BITS Pilani',
        universityEmail: 'priya.sharma@bits.ac.in',
        isVerifiedStudent: true,
        rating: 4.9,
        totalRatings: 8,
        createdAt: '2025-09-01T08:00:00Z',
        updatedAt: '2026-02-10T11:15:00Z',
    },
    {
        id: 'user-3',
        name: 'Rohan Gupta',
        email: 'rohan.gupta@vit.ac.in',
        avatar: '',
        role: 'seller',
        university: 'VIT Vellore',
        universityEmail: 'rohan.gupta@vit.ac.in',
        isVerifiedStudent: true,
        rating: 4.5,
        totalRatings: 6,
        createdAt: '2025-10-12T09:00:00Z',
        updatedAt: '2026-02-15T16:45:00Z',
    },
    {
        id: 'user-4',
        name: 'Sneha Reddy',
        email: 'sneha.reddy@nitw.ac.in',
        avatar: '',
        role: 'seller',
        university: 'NIT Warangal',
        universityEmail: 'sneha.reddy@nitw.ac.in',
        isVerifiedStudent: true,
        rating: 4.7,
        totalRatings: 15,
        createdAt: '2025-07-22T12:00:00Z',
        updatedAt: '2026-01-28T09:20:00Z',
    },
];

// ============================================
// Mock Products
// ============================================
export const mockProducts: Product[] = [
    {
        id: 'prod-1',
        sellerId: 'user-1',
        seller: mockUsers[0],
        title: 'Raymond Premium Navy Blue Suit',
        category: 'suit',
        brand: 'Raymond',
        size: '40',
        color: 'Navy Blue',
        condition: 'like-new',
        originalPrice: 8500,
        sellingPrice: 3200,
        negotiable: true,
        images: ['/api/placeholder/suit-1'],
        university: 'IIT Delhi',
        pickupLocation: 'Hostel Block C, IIT Delhi',
        description: 'Worn only twice for placement interviews. Raymond premium fabric, slim fit. Perfect condition, dry cleaned. Includes suit jacket and matching trousers.',
        status: 'active',
        views: 145,
        wishlistCount: 12,
        createdAt: '2026-01-15T10:00:00Z',
        updatedAt: '2026-02-20T14:30:00Z',
    },
    {
        id: 'prod-2',
        sellerId: 'user-2',
        seller: mockUsers[1],
        title: 'Allen Solly Formal White Shirt',
        category: 'white-shirt',
        brand: 'Allen Solly',
        size: 'M',
        color: 'White',
        condition: 'good',
        originalPrice: 1800,
        sellingPrice: 600,
        negotiable: false,
        images: ['/api/placeholder/shirt-1'],
        university: 'BITS Pilani',
        pickupLocation: 'Meera Bhawan, BITS Pilani',
        description: 'Classic fit white formal shirt. Cotton blend fabric. No stains or tears. Worn for 3-4 interviews.',
        status: 'active',
        views: 89,
        wishlistCount: 5,
        createdAt: '2026-01-28T08:00:00Z',
        updatedAt: '2026-02-18T11:15:00Z',
    },
    {
        id: 'prod-3',
        sellerId: 'user-3',
        seller: mockUsers[2],
        title: 'Woodland Black Formal Oxford Shoes',
        category: 'formal-shoes',
        brand: 'Woodland',
        size: '9',
        color: 'Black',
        condition: 'good',
        originalPrice: 3500,
        sellingPrice: 1200,
        negotiable: true,
        images: ['/api/placeholder/shoes-1'],
        university: 'VIT Vellore',
        pickupLocation: 'Mens Hostel G Block, VIT Vellore',
        description: 'Genuine leather Oxford shoes. Comfortable, well-maintained. Minor scuff on the sole. Size UK 9.',
        status: 'active',
        views: 67,
        wishlistCount: 8,
        createdAt: '2026-02-01T09:00:00Z',
        updatedAt: '2026-02-22T16:45:00Z',
    },
    {
        id: 'prod-4',
        sellerId: 'user-4',
        seller: mockUsers[3],
        title: 'Peter England Charcoal Grey Blazer',
        category: 'blazer',
        brand: 'Peter England',
        size: '42',
        color: 'Charcoal Grey',
        condition: 'like-new',
        originalPrice: 4200,
        sellingPrice: 1800,
        negotiable: true,
        images: ['/api/placeholder/blazer-1'],
        university: 'NIT Warangal',
        pickupLocation: 'Main Gate, NIT Warangal',
        description: 'Single-breasted charcoal grey blazer. Slim fit. Worn once. Looks brand new. Perfect for interviews.',
        status: 'active',
        views: 112,
        wishlistCount: 15,
        createdAt: '2026-02-05T12:00:00Z',
        updatedAt: '2026-02-25T09:20:00Z',
    },
    {
        id: 'prod-5',
        sellerId: 'user-1',
        seller: mockUsers[0],
        title: 'Van Heusen Slim Formal Trouser',
        category: 'pant',
        brand: 'Van Heusen',
        size: '32',
        color: 'Black',
        condition: 'new',
        originalPrice: 2200,
        sellingPrice: 950,
        negotiable: false,
        images: ['/api/placeholder/pant-1'],
        university: 'IIT Delhi',
        pickupLocation: 'Hostel Block C, IIT Delhi',
        description: 'Brand new with tags. Bought wrong size. Slim fit formal black trouser. Perfect crease.',
        status: 'active',
        views: 203,
        wishlistCount: 22,
        createdAt: '2026-02-08T10:00:00Z',
        updatedAt: '2026-02-26T14:30:00Z',
    },
    {
        id: 'prod-6',
        sellerId: 'user-2',
        seller: mockUsers[1],
        title: 'Park Avenue Silk Tie - Maroon Stripe',
        category: 'tie',
        brand: 'Park Avenue',
        size: 'Standard',
        color: 'Maroon',
        condition: 'like-new',
        originalPrice: 800,
        sellingPrice: 300,
        negotiable: true,
        images: ['/api/placeholder/tie-1'],
        university: 'BITS Pilani',
        pickupLocation: 'Meera Bhawan, BITS Pilani',
        description: 'Silk blend tie with subtle diagonal stripes. Deep maroon color. Used in 2 interviews. No stains.',
        status: 'active',
        views: 45,
        wishlistCount: 3,
        createdAt: '2026-02-10T08:00:00Z',
        updatedAt: '2026-02-24T11:15:00Z',
    },
    {
        id: 'prod-7',
        sellerId: 'user-3',
        seller: mockUsers[2],
        title: 'Complete Interview Combo - Suit + Shirt + Tie',
        category: 'combo',
        brand: 'Mixed',
        size: 'L',
        color: 'Navy Blue',
        condition: 'good',
        originalPrice: 12000,
        sellingPrice: 4500,
        negotiable: true,
        images: ['/api/placeholder/combo-1'],
        university: 'VIT Vellore',
        pickupLocation: 'Mens Hostel G Block, VIT Vellore',
        description: 'Complete placement interview combo: Navy blue suit (Raymond), White shirt (Van Heusen), and Navy blue tie. All items in good condition. Save big on the combo!',
        status: 'active',
        views: 287,
        wishlistCount: 34,
        createdAt: '2026-02-12T09:00:00Z',
        updatedAt: '2026-02-27T16:45:00Z',
    },
    {
        id: 'prod-8',
        sellerId: 'user-4',
        seller: mockUsers[3],
        title: 'Louis Philippe White Formal Shirt',
        category: 'white-shirt',
        brand: 'Louis Philippe',
        size: '40',
        color: 'White',
        condition: 'new',
        originalPrice: 2400,
        sellingPrice: 1100,
        negotiable: false,
        images: ['/api/placeholder/shirt-2'],
        university: 'NIT Warangal',
        pickupLocation: 'Main Gate, NIT Warangal',
        description: 'Premium cotton formal shirt. Regular fit. Brand new, never worn. Tags still attached. Size 40.',
        status: 'active',
        views: 156,
        wishlistCount: 18,
        createdAt: '2026-02-14T12:00:00Z',
        updatedAt: '2026-02-26T09:20:00Z',
    },
    {
        id: 'prod-9',
        sellerId: 'user-1',
        seller: mockUsers[0],
        title: 'Bata Black Formal Derby Shoes',
        category: 'formal-shoes',
        brand: 'Bata',
        size: '8',
        color: 'Black',
        condition: 'used',
        originalPrice: 2800,
        sellingPrice: 800,
        negotiable: true,
        images: ['/api/placeholder/shoes-2'],
        university: 'IIT Delhi',
        pickupLocation: 'Hostel Block C, IIT Delhi',
        description: 'Well-used but still sturdy. Polished recently. Some wear on heels. Great budget option for interviews.',
        status: 'active',
        views: 92,
        wishlistCount: 6,
        createdAt: '2026-02-16T10:00:00Z',
        updatedAt: '2026-02-27T14:30:00Z',
    },
    {
        id: 'prod-10',
        sellerId: 'user-2',
        seller: mockUsers[1],
        title: 'Arrow Navy Blue Blazer - Slim Fit',
        category: 'blazer',
        brand: 'Arrow',
        size: '38',
        color: 'Navy Blue',
        condition: 'like-new',
        originalPrice: 5500,
        sellingPrice: 2200,
        negotiable: true,
        images: ['/api/placeholder/blazer-2'],
        university: 'BITS Pilani',
        pickupLocation: 'Meera Bhawan, BITS Pilani',
        description: 'Slim fit blazer by Arrow. Stunning navy blue color. Worn once for final placement round. Dry cleaned and stored properly.',
        status: 'active',
        views: 178,
        wishlistCount: 21,
        createdAt: '2026-02-18T08:00:00Z',
        updatedAt: '2026-02-27T11:15:00Z',
    },
    {
        id: 'prod-11',
        sellerId: 'user-3',
        seller: mockUsers[2],
        title: 'Black Formal Trouser - Regular Fit',
        category: 'pant',
        brand: 'Blackberrys',
        size: '34',
        color: 'Black',
        condition: 'good',
        originalPrice: 1900,
        sellingPrice: 700,
        negotiable: false,
        images: ['/api/placeholder/pant-2'],
        university: 'VIT Vellore',
        pickupLocation: 'Mens Hostel G Block, VIT Vellore',
        description: 'Regular fit formal trouser. Good condition, iron-pressed. No visible wear marks. Comfortable for long interview days.',
        status: 'active',
        views: 65,
        wishlistCount: 4,
        createdAt: '2026-02-20T09:00:00Z',
        updatedAt: '2026-02-27T16:45:00Z',
    },
    {
        id: 'prod-12',
        sellerId: 'user-4',
        seller: mockUsers[3],
        title: 'Premium Silk Tie Collection (3 Ties)',
        category: 'tie',
        brand: 'Mixed',
        size: 'Standard',
        color: 'Navy Blue',
        condition: 'like-new',
        originalPrice: 2400,
        sellingPrice: 900,
        negotiable: true,
        images: ['/api/placeholder/tie-2'],
        university: 'NIT Warangal',
        pickupLocation: 'Main Gate, NIT Warangal',
        description: '3 premium ties - Navy blue solid, Maroon stripe, Black micro dot. All silk blend. Excellent condition. Perfect variety for multiple interviews.',
        status: 'active',
        views: 134,
        wishlistCount: 16,
        createdAt: '2026-02-22T12:00:00Z',
        updatedAt: '2026-02-28T09:20:00Z',
    },
];

// Price suggestion logic
export function suggestPrice(originalPrice: number, condition: string): number {
    const multipliers: Record<string, number> = {
        new: 0.7,
        'like-new': 0.55,
        good: 0.4,
        used: 0.25,
    };
    return Math.round(originalPrice * (multipliers[condition] || 0.4));
}

// Format price for Indian Rupees
export function formatPrice(price: number): string {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
    }).format(price);
}

// Calculate discount percentage
export function calcDiscount(original: number, selling: number): number {
    return Math.round(((original - selling) / original) * 100);
}

// Time ago helper
export function timeAgo(dateStr: string): string {
    const now = new Date();
    const date = new Date(dateStr);
    const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

    if (seconds < 60) return 'Just now';
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`;
    return date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
}
